### PR TITLE
Sequelize security patch

### PR DESCRIPTION
**Pull request by theninj4**

### CODE REVIEW

**Comment by theninj4** [comment]
See #38

**Comment by pmcnr-hx** [comment]
The Sequelize changes seem to have altered the logic somehow and broken some tests... 😞

**Comment by pmcnr-hx** [comment]
I spent a few hours trying to make this work and it's a bit of a can of worms because of the way included resources count behaviour changed from `3.23.4` to `3.23.6` which completely breaks our pagination logic. Maybe it's worth waiting for `4.0.0` to be released and just go with that instead.

**Comment by pmcnr-hx** [comment]
Closing this in favour of #42, which enables and does the Sequelize upgrade.

**Pull request closed without merging**
