### PR TITLE
split out the model generation code

### PR DESCRIPTION
**Pull request by championswimmer**
We have some extra types like JSONB and ARRAY(NUMERIC) we can use for Postgres, let's take advantage of that.

### CODE REVIEW

**Comment by championswimmer** [comment]
@pmcnr-hx 
So I've split out model generation into seprate modules. Using a common 'default' module for everything other than Postgres right now, as my optimisations are only for Postgres. For others, it's the same.

**Comment by aledalgrande** [comment]
@championswimmer could this also take care of #53 as you are splitting out by dialect?

**Comment by championswimmer** [comment]
@aledalgrande this fixes #53 by making [type] a virtual field

**Comment by championswimmer** [comment]
also, @aledalgrande do you think I can target postgres >= 9.4 ??
Will allow using JSONB type

Are you using < v9.4 ?

**Comment by aledalgrande** [comment]
@championswimmer using latest stable, so it's fine!

**Comment by championswimmer** [comment]
Continues to #75

**Pull request closed without merging**
