### PR TITLE
fix(sequelize): properly freeze table names

### PR DESCRIPTION
**Pull request by oliversalzburg**
According to http://docs.sequelizejs.com/manual/installation/getting-started.html#application-wide-model-options the property needs to be defined in the `define` block.

### CODE REVIEW

**Comment by pmcnr-hx** [comment]
Thank you for the contributing this @oliversalzburg. I updated `jsonapi-server` dependencies today and I will need to update this package to the use latest `jsonapi-server` and make sure all the tests pass, which I should be able to do soon.

**Comment by championswimmer** [comment]
Any updates on this ?

**Comment by paparomeo** [comment]
@championswimmer: I'm doing work on the project tomorrow and should be able to merge this.

**Comment by pmcnr-hx** [comment]
I'll merge this as soon as we've been able to fix the broken test when we update to the latest dependencies. Like I mentioned in your pull request @championswimmer, the reason for the test failing is no entirely trivial, since I don't think we have tested this handler with the new GraphQL support in the server. I'll com back to it tomorrow.

**Pull request merged**
