### PR TITLE
update to use latest dependencies

### PR DESCRIPTION
**Pull request by championswimmer**
synced with same dependency versions as `jsonapi-server`

### CODE REVIEW

**Comment by championswimmer** [comment]
@pmcnr-hx please take a look

**Comment by pmcnr-hx** [comment]
I was trying to do the same today but one of the tests is failing. It's not entirely trivial to spot why it is failing and I have to stop for today, but I will come back to it tomorrow. Once that test is passing we can do a release with all the dependencies updated.

**Comment by championswimmer** [comment]
@pmcnr-hx there was lint error in mine because of using rest-spread `...` operator. I have removed that now

**Comment by championswimmer** [comment]
@pmcnr-hx it works with Postgres now. Don't understand why MySQL fails

**Comment by pmcnr-hx** [comment]
Thanks for the excellent work @championswimmer! As you have already noticed, I have merged a few of the outstanding PRs and updated the dependencies. Could you possibly rebase on master so the PR is cleaner and only includes commits for your fixes? If not, I'll cherry pick your fixes tomorrow into a branch off master and we should be able to do a final 2.0.0 release with all the tests passing.

**Comment by championswimmer** [comment]
@pmcnr-hx done. now we are passing all 149 tests in mysql **as well as** postgres both

**Comment by championswimmer** [comment]
Woohoo! Travis passed.

**Comment by championswimmer** [comment]
@pmcnr-hx this looks good now ?

**Pull request merged**
